#!/usr/bin/env python3

import pandas as pd
import pymongo

def main():
    # 1. Read the CSV file generated by your existing code
    csv_file = "hespress_politics_comments.csv"
    try:
        df_comments = pd.read_csv(csv_file)
        print(f"Loaded {len(df_comments)} comments from {csv_file}.")
    except FileNotFoundError:
        print(f"Error: {csv_file} not found.")
        return
    except Exception as e:
        print(f"Error reading {csv_file}: {e}")
        return

    # 2. Connect to MongoDB Atlas
    #    Make sure to update with your actual credentials and cluster info.
    CONNECTION_STRING = (
        "mongodb+srv://YOUR_USERNAME:YOUR_PASSWORD"
        "@YOUR_CLUSTER.mongodb.net/?retryWrites=true&w=majority"
    )
    client = pymongo.MongoClient(CONNECTION_STRING)

    # 3. Select your database and collection
    db = client["YOUR_DATABASE_NAME"]
    collection = db["hespress_politics_comments"]  # Choose the collection name

    # 4. Convert DataFrame to a list of dictionaries (MongoDB-compatible format)
    records_to_insert = df_comments.to_dict(orient="records")

    # 5. Insert the records into MongoDB
    try:
        result = collection.insert_many(records_to_insert)
        print(f"Successfully inserted {len(result.inserted_ids)} records into MongoDB.")
    except Exception as e:
        print(f"Error inserting records into MongoDB: {e}")

if __name__ == "__main__":
    main()
