[theme]
base = "dark"
primaryColor = "#FF416C"                  # Vibrant pink-red for action buttons and highlights
backgroundColor = "#0D1117"               # Deep, true black-blue background (GitHub dark vibe)
secondaryBackgroundColor = "#161B22"      # Slightly lighter shade for containers/cards
textColor = "#E6EDF3"                     # Soft off-white for readability
font = "monospace"                        # Techy feel (options: "sans serif", "serif", "monospace")
[client]
showSidebarNavigation = true