[openai]
api_key = "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"
default_model = "gpt-3.5-turbo"               # Default model to use (e.g., "gpt-3.5-turbo" or "gpt-4")
max_tokens = 200                           # Default max tokens for responses
cost_optimization = true                    # Enable cost optimization (true/false)

[mongodb]
connection_string = "mongodb://localhost:27017"  # MongoDB connection string
database = "CivicCatalyst"                       # Database name

[qdrant]
host = "localhost"                           # Qdrant host
port = 6333                                  # Qdrant port